DROP TABLE IF EXISTS bank_user;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS fruit_table;

CREATE TABLE IF NOT EXISTS fruit_table
(
    id_fruit   BIGINT AUTO_INCREMENT PRIMARY KEY,
    fruit_name VARCHAR(255),
    provider_code BIGINT
);

CREATE TABLE IF NOT EXISTS bank_user
(
    ID_usr   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(255),
    AMOUNT      BIGINT,
    USER_ID BIGINT,
    foreign key (USER_ID) references bank_user
);

CREATE SEQUENCE HIBERNATE_SEQUENCE MINVALUE 1;
