<!DOCTYPE HTML>
<html>
<head>
    <title>Getting Started: Serving Web Content</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>    
    <h2>Home page from Freemaker !!!</h2>
    <h1>Get your greeting from <a href="/freemaker?name=Java Developer">FREEMAKER</a></h1>
    <p>Если бы не было этой страницы и метода homePageMethod, домашней бы запускалася спрингом страница в resources/static/index.html</p>
</body>
</html>